//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace AYKJ.GISInterface.AykjCreateShp {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.ObjectModel.ObservableCollection<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AykjCreateShp.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ToShp", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType))]
        System.IAsyncResult BeginToShp(AYKJ.GISInterface.AykjCreateShp.ToShpRequest request, System.AsyncCallback callback, object asyncState);
        
        AYKJ.GISInterface.AykjCreateShp.ToShpResponse EndToShp(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToShpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToShp", Namespace="http://tempuri.org/", Order=0)]
        public AYKJ.GISInterface.AykjCreateShp.ToShpRequestBody Body;
        
        public ToShpRequest() {
        }
        
        public ToShpRequest(AYKJ.GISInterface.AykjCreateShp.ToShpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToShpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstShpName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstJsons;
        
        public ToShpRequestBody() {
        }
        
        public ToShpRequestBody(AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstShpName, AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstJsons) {
            this.lstShpName = lstShpName;
            this.lstJsons = lstJsons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToShpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToShpResponse", Namespace="http://tempuri.org/", Order=0)]
        public AYKJ.GISInterface.AykjCreateShp.ToShpResponseBody Body;
        
        public ToShpResponse() {
        }
        
        public ToShpResponse(AYKJ.GISInterface.AykjCreateShp.ToShpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToShpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToShpResult;
        
        public ToShpResponseBody() {
        }
        
        public ToShpResponseBody(string ToShpResult) {
            this.ToShpResult = ToShpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : AYKJ.GISInterface.AykjCreateShp.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToShpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ToShpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<AYKJ.GISInterface.AykjCreateShp.Service1Soap>, AYKJ.GISInterface.AykjCreateShp.Service1Soap {
        
        private BeginOperationDelegate onBeginToShpDelegate;
        
        private EndOperationDelegate onEndToShpDelegate;
        
        private System.Threading.SendOrPostCallback onToShpCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<ToShpCompletedEventArgs> ToShpCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AYKJ.GISInterface.AykjCreateShp.Service1Soap.BeginToShp(AYKJ.GISInterface.AykjCreateShp.ToShpRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginToShp(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginToShp(AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstShpName, AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstJsons, System.AsyncCallback callback, object asyncState) {
            AYKJ.GISInterface.AykjCreateShp.ToShpRequest inValue = new AYKJ.GISInterface.AykjCreateShp.ToShpRequest();
            inValue.Body = new AYKJ.GISInterface.AykjCreateShp.ToShpRequestBody();
            inValue.Body.lstShpName = lstShpName;
            inValue.Body.lstJsons = lstJsons;
            return ((AYKJ.GISInterface.AykjCreateShp.Service1Soap)(this)).BeginToShp(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AYKJ.GISInterface.AykjCreateShp.ToShpResponse AYKJ.GISInterface.AykjCreateShp.Service1Soap.EndToShp(System.IAsyncResult result) {
            return base.Channel.EndToShp(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndToShp(System.IAsyncResult result) {
            AYKJ.GISInterface.AykjCreateShp.ToShpResponse retVal = ((AYKJ.GISInterface.AykjCreateShp.Service1Soap)(this)).EndToShp(result);
            return retVal.Body.ToShpResult;
        }
        
        private System.IAsyncResult OnBeginToShp(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstShpName = ((AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType)(inValues[0]));
            AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstJsons = ((AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType)(inValues[1]));
            return this.BeginToShp(lstShpName, lstJsons, callback, asyncState);
        }
        
        private object[] OnEndToShp(System.IAsyncResult result) {
            string retVal = this.EndToShp(result);
            return new object[] {
                    retVal};
        }
        
        private void OnToShpCompleted(object state) {
            if ((this.ToShpCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ToShpCompleted(this, new ToShpCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ToShpAsync(AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstShpName, AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstJsons) {
            this.ToShpAsync(lstShpName, lstJsons, null);
        }
        
        public void ToShpAsync(AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstShpName, AYKJ.GISInterface.AykjCreateShp.ArrayOfAnyType lstJsons, object userState) {
            if ((this.onBeginToShpDelegate == null)) {
                this.onBeginToShpDelegate = new BeginOperationDelegate(this.OnBeginToShp);
            }
            if ((this.onEndToShpDelegate == null)) {
                this.onEndToShpDelegate = new EndOperationDelegate(this.OnEndToShp);
            }
            if ((this.onToShpCompletedDelegate == null)) {
                this.onToShpCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnToShpCompleted);
            }
            base.InvokeAsync(this.onBeginToShpDelegate, new object[] {
                        lstShpName,
                        lstJsons}, this.onEndToShpDelegate, this.onToShpCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AYKJ.GISInterface.AykjCreateShp.Service1Soap CreateChannel() {
            return new Service1SoapClientChannel(this);
        }
        
        private class Service1SoapClientChannel : ChannelBase<AYKJ.GISInterface.AykjCreateShp.Service1Soap>, AYKJ.GISInterface.AykjCreateShp.Service1Soap {
            
            public Service1SoapClientChannel(System.ServiceModel.ClientBase<AYKJ.GISInterface.AykjCreateShp.Service1Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginToShp(AYKJ.GISInterface.AykjCreateShp.ToShpRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ToShp", _args, callback, asyncState);
                return _result;
            }
            
            public AYKJ.GISInterface.AykjCreateShp.ToShpResponse EndToShp(System.IAsyncResult result) {
                object[] _args = new object[0];
                AYKJ.GISInterface.AykjCreateShp.ToShpResponse _result = ((AYKJ.GISInterface.AykjCreateShp.ToShpResponse)(base.EndInvoke("ToShp", _args, result)));
                return _result;
            }
        }
    }
}
